### ISSUE TITLE
Thursday, 7/8 To Do List

### ISSUE THREAD

**Issue by SophieDeBenedetto** [groxio-learning/grapevine#11]
👋 Hello all! Since I'm out of the office this week and I can't join our usual Thursday session, I wrote up this issue to describe the list of To Dos that we need to tackle next. You guys can tackle this list however you decide is best 😄 

## This Week

* Rename `Resource` module and database table to `Post`, see convo [here](https://github.com/groxio-learning/grapevine/issues/7#issuecomment-875127704) for reference. 
  * NOTE: Since we want to rename the table and schema module _and_ since we want to build some LiveView code to act as the front-end for managing posts, as described here https://github.com/groxio-learning/grapevine/issues/7, I'd suggest using the Phoenix Live generator to generate a _new_ table and schema _and_ the associated routes and live views. Running this generator https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Live.html will generate all the code you need to serve as the foundation for our LiveView CRUD app, including code that uses [Live actions](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.Router.html#live/4-actions-and-live-navigation) for routing. Then, we can simply delete the old migrations and schema files describing the old `Resource` module and table.
* Finish the To Do's from last week, outlined [here](https://github.com/groxio-learning/grapevine/issues/2#issuecomment-872594736), in particular this item:
  * Define a context module that exposes these functions:
    * Function to create a post that belongs to a given user.
    * There should be a test for the context and this function.
* Then, if you guys have time, you can get started on this issue https://github.com/groxio-learning/grapevine/issues/7. I'd suggest getting started by learning more about how to use live actions for routing. 
  * See the docs here https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.Router.html#live/4-actions-and-live-navigation

## Next Week
Next week we will finish the deployment and CI setup. I'm still waiting on:

* Gigelixir access for myself so I can fetch the secret credentials
* Repo owner access here so I can set the secrets and add branch protections 

I'll also follow up with GitHub when I'm back in the office next week about getting some more organization seats so that we can get more admin access set up.

**Comment by SophieDeBenedetto** [comment]
👋 hey @herminiotorres @cristineguadelupe @JulianaHelena5 @grace-in-wonderland @adolfont and whoever else will join our group on Thursday! Please use this issue to guide the to-do list for tomorrow evening's session 😄

**Comment by jacquelineIO** [comment]
@herminiotorres @cristineguadelupe @JulianaHelena5 @grace-in-wonderland @adolfont @SophieDeBenedetto -- 
today's session was: @herminiotorres @JulianaHelena5 and me
We finished the first 2 big bullet items, which was to rename `Resource` to `Post` and write and test the create function for `Post`. 

We did not get to Users Can Manage Resources #7
