### ISSUE TITLE
Validade URL on Post module

### ISSUE THREAD

**Issue by herminiotorres** [groxio-learning/grapevine#27]
Hi all, 

I think we must validate the format for the URL field on Post. And I share here on this issue a good start where we can use for our full implementation.

```elixir
valid? = fn url ->
  uri = URI.parse(url)
  uri.scheme != nil && uri.host =~ ~r/(www\.)?[[:alnum:]]\.[[:alnum:]]/i && uri.host =~ ~r/\A[^\.]/i
end

urls = [
  "http://vk.com",
  "http://semantic-ui.com/collections/menu.html",
  "https://translate.yandex.ru/?text=poll&lang=en-ru",
  "www.vk.com",
  ".vk.com",
  "abdeeej",
  "http://vk",
  "http://.vk.com"
]

urls |> Enum.map(valid?) |> IO.inspect

[true, true, true, false, false, false, false, false]
```

Link to implement a custom validate with [Ecto.Changeset.validate_change/3](https://hexdocs.pm/ecto/Ecto.Changeset.html#validate_change/3), to use it this previous code to implement our `validade_urls` function inside the `Grapevine.Post` module.

**Comment by SophieDeBenedetto** [comment]
Closed by #31
